/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.gui;

import javax.swing.*;

/**
 *
 * @author angelvintos
 */
public class PlacesEvent extends javax.swing.JFrame {

    private MenuBeeVent formularioPrincipal;
    /**
     * Creates new form PacesEvent
     */
    public static int placeId;

    public PlacesEvent() {
        initComponents();
    }

    public PlacesEvent(MenuBeeVent nuevoFrame) {
        this.formularioPrincipal = nuevoFrame;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonPlace1 = new javax.swing.JButton();
        jButtonPlace2 = new javax.swing.JButton();
        jButtonPlace3 = new javax.swing.JButton();
        jLabelSerraparera = new javax.swing.JLabel();
        jLabelSendo = new javax.swing.JLabel();
        jLabelConejo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonPlace1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gui/Images/MicrosoftTeams-image (1).png"))); // NOI18N
        jButtonPlace1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace1ActionPerformed(evt);
            }
        });

        jButtonPlace2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gui/Images/MicrosoftTeams-image (2).png"))); // NOI18N
        jButtonPlace2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace2ActionPerformed(evt);
            }
        });

        jButtonPlace3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/gui/Images/MicrosoftTeams-image (3).png"))); // NOI18N
        jButtonPlace3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlace3ActionPerformed(evt);
            }
        });

        jLabelSerraparera.setText("Calle Serraparera 270");

        jLabelSendo.setText("Calle Sendo Carbon 23");

        jLabelConejo.setText("Calle Conejo Bueno 30");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addComponent(jLabelSerraparera)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelSendo)
                .addGap(427, 427, 427))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jButtonPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(352, 352, 352)
                        .addComponent(jButtonPlace3, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(644, 644, 644)
                        .addComponent(jLabelConejo)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonPlace1, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlace2, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelSerraparera, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelSendo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonPlace3, javax.swing.GroupLayout.PREFERRED_SIZE, 438, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelConejo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlace1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace1ActionPerformed
        // TODO add your handling code here:

        JOptionPane.showMessageDialog(this, "Seleccionaste Serraparera");
        placeId = 1;
        // Crear una instancia de MenuBeeVent
        // Hacer visible el JFrame MenuBeeVent
        formularioPrincipal.setVisible(true);
        // Establecer la visibilidad de la etiqueta correspondiente al lugar seleccionado
        formularioPrincipal.setSerrapareraVisible(true);
        formularioPrincipal.setSendoCarbonVisible(false);
        formularioPrincipal.setConejoBuenoVisible(false);
        // Cerrar el JFrame actual        
        this.dispose();
    }//GEN-LAST:event_jButtonPlace1ActionPerformed

    private void jButtonPlace2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace2ActionPerformed
        // TODO add your handling code here:
        // Mostrar un mensaje correspondiente al lugar
        placeId = 2;

        JOptionPane.showMessageDialog(this, "Seleccionaste Sendo Carbon");

        formularioPrincipal.setVisible(true);
        // Establecer la visibilidad de la etiqueta correspondiente al lugar seleccionado
        
        formularioPrincipal.setSerrapareraVisible(false);
        formularioPrincipal.setSendoCarbonVisible(true);
        formularioPrincipal.setConejoBuenoVisible(false);

        // Cerrar el JFrame actual
        this.dispose();

    }//GEN-LAST:event_jButtonPlace2ActionPerformed

    private void jButtonPlace3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlace3ActionPerformed
        // TODO add your handling code here:

        placeId = 3;

        JOptionPane.showMessageDialog(this, "Seleccionaste Conejo Bueno");

        // Hacer visible el JFrame MenuBeeVent
        formularioPrincipal.setVisible(true);
        // Establecer la visibilidad de la etiqueta correspondiente al lugar seleccionado
        formularioPrincipal.setSendoCarbonVisible(false);
        formularioPrincipal.setSerrapareraVisible(false);
        formularioPrincipal.setConejoBuenoVisible(true);

        // Cerrar el JFrame actual
        this.dispose();

    }//GEN-LAST:event_jButtonPlace3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PlacesEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PlacesEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PlacesEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PlacesEvent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PlacesEvent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPlace1;
    private javax.swing.JButton jButtonPlace2;
    private javax.swing.JButton jButtonPlace3;
    private javax.swing.JLabel jLabelConejo;
    private javax.swing.JLabel jLabelSendo;
    private javax.swing.JLabel jLabelSerraparera;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
